### ISSUE TITLE
首页加载时间过长程序无法正常运行

### ISSUE THREAD

**Issue by Cloudslife** [Carpenter-MK1/MaaHatsuboshiTA#2]
进行第二次任务时如在首页加载时间过长程序会卡死
![Screenshot_2024 05 26_13 19 07 692](https://github.com/Carpenter-MK1/MaaHatsuboshiTA/assets/111268852/6c386515-446a-4bbe-a1df-941d23de383b)
![屏幕截图 2024-05-26 131929](https://github.com/Carpenter-MK1/MaaHatsuboshiTA/assets/111268852/e92b0b89-3a6c-416a-a2fc-8560bac21c2d)

**Comment by Carpenter-MK1** [comment]
请问软件版本是1.0.1还是1.0.2呢，如果是老版本可以下载新的看一下有没有改善。

**Comment by Cloudslife** [comment]
1.0.2不会卡死了，感谢
