### ISSUE TITLE
运行任务后模拟器无反应，显示Task.Failed Clear_Data

### ISSUE THREAD

**Issue by FlandreCN** [Carpenter-MK1/MaaHatsuboshiTA#4]
MuMu模拟器版本为V3.8.25 (2927)，分辨率900*1600 DPI240
在游戏标题界面运行任务后模拟器无反应，过几秒后显示Task.Failed Clear_Data

CLI界面：
```
Welcome to use Maa Project Interface CLI!
MaaFramework: v1.8.0-beta.2

Version: v1.0.2

### Current configuration ###

Controller:

        安卓端
                F:/emulator/MuMuPlayer-12.0/shell/adb.exe
                127.0.0.1:16384

Resource:

        Official

Tasks:

        - 刷初始（开始前将游戏退出至最外层标题页）
                - 需要SSR支援卡数量:: 4张

### Select action ###

        1. Switch controller
        2. Switch resource
        3. Add task
        4. Move task
        5. Delete task
        6. Run tasks
        7. Exit

Please input [1-7]: 6

nemu_connect instance_name: ginstance1393599749797255600
on_maafw_notify: Task.Started Clear_Data
on_maafw_notify: Task.Failed Clear_Data
### All tasks have been completed ###


Press Enter to continue...
```

**Comment by Carpenter-MK1** [comment]
可以尝试修改像素密度为320DPI，看看有没有改善

**Comment by FlandreCN** [comment]
> 可以尝试修改像素密度为320DPI，看看有没有改善

已修改为320DPI，错误依旧出现

**Comment by Carpenter-MK1** [comment]
> > 可以尝试修改像素密度为320DPI，看看有没有改善
> 
> 已修改为320DPI，错误依旧出现

请上传debug文件夹中的maa.log文件，之后我这边会尝试复现

**Comment by FlandreCN** [comment]
> > > 可以尝试修改像素密度为320DPI，看看有没有改善
> > 
> > 
> > 已修改为320DPI，错误依旧出现
> 
> 请上传debug文件夹中的maa.log文件，之后我这边会尝试复现

[maa.log](https://github.com/Carpenter-MK1/MaaHatsuboshiTA/files/15446947/maa.log)

**Comment by Carpenter-MK1** [comment]
一个猜想，你的分辨率设置是否为“平板版”的1600 * 900？MAA框架目前没有适配自动旋转，你需要将分辨率设置为“手机版”的900 * 1600。

**Comment by FlandreCN** [comment]
![image](https://github.com/Carpenter-MK1/MaaHatsuboshiTA/assets/65822851/a4f88358-422f-4fcc-9878-15e1e399b9ac)
设置的是手机版没错。应该不是这个问题

**Comment by Carpenter-MK1** [comment]
🤔我已经按照你的设置还原进行了测试，目前是没有问题的。或许你可以尝试一下使用新版本？

**Comment by FlandreCN** [comment]
> 🤔我已经按照你的设置还原进行了测试，目前是没有问题的。或许你可以尝试一下使用新版本？

使用新版本依然会出现同样的问题，但我使用另外一台也是win11的设备运行是完全正常的，两台设备模拟器设置完全一致，可以排除设置问题了，不知道是什么奇怪的兼容性bug。。

**Comment by Carpenter-MK1** [comment]
其他用户反馈说关闭mumu的后台保活可以运行，你可以先尝试一下

**Comment by FlandreCN** [comment]
> 其他用户反馈说关闭mumu的后台保活可以运行，你可以先尝试一下

关闭后台保活后可以正常运行了，谢谢
