### ISSUE TITLE
运行后模拟器无反应，最后显示### All tasks have been completed ###

### ISSUE THREAD

**Issue by BoloRin** [Carpenter-MK1/MaaHatsuboshiTA#5]
使用mumu模拟器，版本号v.3.8.25（2927），显示分辨率为手机版900x1600 (DPI320)，启动后模拟器无反应，直接显示所有任务完成

```
Welcome to use Maa Project Interface CLI!
MaaFramework: v1.8.0

Version: v1.0.4

### Current configuration ###

Controller:

        安卓端
                G:/MuMu Player 12/shell/adb.exe
                127.0.0.1:16384

Resource:

        Official

Tasks:

        - 刷初始（开始前将游戏退出至最外层标题页）
                - 需要SSR支援卡数量:: 5张

### Select action ###

        1. Switch controller
        2. Switch resource
        3. Add task
        4. Move task
        5. Delete task
        6. Run tasks
        7. Exit

Please input [1-7]: 6

nemu_connect instance_name: ginstance1393606894761293000
on_maafw_notify: Task.Started Clear_Data
on_maafw_notify: Task.Failed Clear_Data
### All tasks have been completed ###


Press Enter to continue...
```
[maa.log](https://github.com/Carpenter-MK1/MaaHatsuboshiTA/files/15450128/maa.log)

**Comment by BoloRin** [comment]
换用蓝叠模拟器后能用了，不知道是不是mumu的问题

**Comment by Carpenter-MK1** [comment]
确认为无法识别到menu按钮，会在下个版本尝试优化，届时请更新版本看一下效果。如果问题依然存在劳烦进群反馈。

**Comment by Carpenter-MK1** [comment]
其他用户反馈说关闭mumu的后台保活可以运行，你可以先尝试一下

**Comment by hrz6976** [comment]
我也遇到了一样的问题。看了下log，识别到的区域基本是对的，OpenCV给的Score太低了导致结果被筛掉了。可以试下把TemplateMatch的threshold改低一些：
```json
    "Enter_Clear_Data": {
        "recognition": "TemplateMatch",
        "template": "icon_start_clear_data.png",
        "action": "Click",
        "threshold": 0.3,
        "post_delay": 800,
        "next": [
            "Click_Clear_Data"
        ]
    },
```

**Comment by hrz6976** [comment]
我试了下基于OCR的办法不大行，MAA默认只带了中英文的paddle ocr模型，识别日语效果很差。PaddleOCR v4的多语言模型没有公开，可以尝试下[v3日语模型](https://github.com/Mushroomcat9998/PaddleOCR/blob/main/doc/doc_en/multi_languages_en.md)

**Comment by BoloRin** [comment]
我尝试了一下蓝叠模拟器，蓝叠是能用的，怪欸

**Comment by Carpenter-MK1** [comment]
> 我尝试了一下蓝叠模拟器，蓝叠是能用的，怪欸

1. 关于匹配，我下个版本会考虑涂了绿幕的模板来改善效果
2. 尝试使用过框架自带的ocr日语效果不太行，如果1还是没有效果那么考虑换新的ocr模型识别文字
3. 我的mumu一直都可以，很怪。怀疑和运行效果有关，高流畅度更容易出现错误

**Comment by hrz6976** [comment]
我实测用石头10连还是可能会点到1连（明明10连按钮的score更高），可以指定roi解决：
```
    "Gacha_1": {
        "recognition": "TemplateMatch",
        "template": "icon_gacha_with_diamonds.png","threshold": 0.5,
        "action": "Click",
        "roi": [
            360,
            540,
            360,
            540
        ],
        "next": [
            "Gacha_With_Diamonds_Confirm"
        ]
    },
```

**Comment by Carpenter-MK1** [comment]
> 我实测用石头10连还是可能会点到1连（明明10连按钮的score更高），可以指定roi解决：
> 
> ```
>     "Gacha_1": {
>         "recognition": "TemplateMatch",
>         "template": "icon_gacha_with_diamonds.png","threshold": 0.5,
>         "action": "Click",
>         "roi": [
>             360,
>             540,
>             360,
>             540
>         ],
>         "next": [
>             "Gacha_With_Diamonds_Confirm"
>         ]
>     },
> ```

谢谢提议！下个版本我会优化进代码里
