### ISSUE TITLE
運行一次就清除失敗。

### ISSUE THREAD

**Issue by hiyohiyoovo** [Carpenter-MK1/MaaHatsuboshiTA#6]
Welcome to use Maa Project Interface CLI!
MaaFramework: v1.8.1

Version: v1.1.0

### Current configuration ###

Controller:

        安卓端
                F:/mumu/MuMuPlayer-12.0/shell/adb.exe
                127.0.0.1:16384

Resource:

        Official

Tasks:

        - 刷初始（开始前将游戏退出至最外层标题页）
                - 不同SSR支援卡数量: 4张
                - 第一张指定卡: 【~~~不指定~~~】
                - 第二张指定卡: 【~~~不指定~~~】

### Select action ###

        1. Switch controller
        2. Switch resource
        3. Add task
        4. Move task
        5. Delete task
        6. Run tasks
        7. Exit

Please input [1-7]: 6

nemu_connect instance_name: ginstance1393618319537420100
[2024-05-28 18:16:50.401][ERR][Px18644][Tx8440][ScreencapHelper.cpp][L71][MaaNS::CtrlUnitNs::ScreencapHelper::process_data] skip retry decoding and decode failed!
on_maafw_notify: Task.Started Clear_Data
on_maafw_notify: Task.Failed Clear_Data
### All tasks have been completed ###

**Comment by Carpenter-MK1** [comment]
请问是偶然发生的还是每一次都会发生？能否上传debug文件夹下的maa.log文件

**Comment by hiyohiyoovo** [comment]
> 请问是偶然发生的还是每一次都会发生？ 能否上传debug文件夹下的maa.log文件

是每一次都發生。

**Comment by hiyohiyoovo** [comment]
[maa.log](https://github.com/Carpenter-MK1/MaaHatsuboshiTA/files/15468991/maa.log)

**Comment by hiyohiyoovo** [comment]
刪過文件，因為重啟還卡著，不知道這log裡有沒有你需要的，或則等我有空再打幾次存下log重新發送下。

**Comment by yokaimeow** [comment]
1.0.4版本也出现了，感觉是今天下午游戏闪断之后出现的

**Comment by yokaimeow** [comment]
[maa.log](https://github.com/Carpenter-MK1/MaaHatsuboshiTA/files/15469250/maa.log)
单次运行的log

**Comment by hiyohiyoovo** [comment]
nemu_connect instance_name: ginstance1393618959650054800
on_maafw_notify: Task.Started Clear_Data
on_maafw_notify: Task.Failed Clear_Data
### All tasks have been completed ### 
現在狀況就是一次運行結束後就不會再啟了。

**Comment by hiyohiyoovo** [comment]
[maa.log](https://github.com/Carpenter-MK1/MaaHatsuboshiTA/files/15469259/maa.log)

**Comment by hiyohiyoovo** [comment]
> 1.0.4版本也出现了，感觉是今天下午游戏闪断之后出现的

下午更新前我就使用了，一樣的狀況。跟更新沒關係。

**Comment by yokaimeow** [comment]
> > 1.0.4版本也出现了，感觉是今天下午游戏闪断之后出现的
> 
> 下午更新前我就使用了，一樣的狀況。跟更新沒關係。

现在我换回1.0.4可以运行几次才结束，用1.1.0运行一次必结束

**Comment by hiyohiyoovo** [comment]
> > > 1.0.4版本也出现了，感觉是今天下午游戏闪断之后出现的
> > 
> > 
> > 下午更新前我就使用了，一樣的狀況。跟更新沒關係。
> 
> 现在我换回1.0.4可以运行几次才结束，用1.1.0运行一次必结束

不是我一個人有問題就行了x這就不是我本身問題了。

**Comment by hiyohiyoovo** [comment]
目前1.0.4已經重複再啟7 8 次了無問題，1.1.0運行一次就不消除賬號再啟動了。

**Comment by yokaimeow** [comment]
目前1.0.4 1.1.0 都可以持续刷了，没出现清除任务失败

**Comment by Carpenter-MK1** [comment]
我这边测试把匹配图片修改为了green_mask版本同时下调了阈值，以后应该不会有这个问题了

**Comment by hiyohiyoovo** [comment]
> 我这边测试把匹配图片修改为了green_mask版本同时下调了阈值，以后应该不会有这个问题了

不知道能不能加個數次計算，就能知道自己刷了多少次刷出來了自己想出來的

**Comment by Carpenter-MK1** [comment]
更新了新版本，请下载看看问题还有没有出现。
目前MAA框架我还没有研究出写本地的方法，所以暂时做不了。或许未来会实装，或许（

**Comment by yokaimeow** [comment]
最新版本一直执行没啥问题，这个issue可以close，thk

**Comment by hiyohiyoovo** [comment]
> 更新了新版本，请下载看看问题还有没有出现。 目前MAA框架我还没有研究出写本地的方法，所以暂时做不了。或许未来会实装，或许（

新版本擁有了新的bugx  偶爾會不抽完就回倉庫，然後就退出了。

**Comment by hiyohiyoovo** [comment]
> > 更新了新版本，请下载看看问题还有没有出现。 目前MAA框架我还没有研究出写本地的方法，所以暂时做不了。或许未来会实装，或许（
> 
> 新版本擁有了新的bugx 偶爾會不抽完就回倉庫，然後就退出了。

狀況為UP十連抽完滑到普池不會進行抽取，就會直接回倉庫。

**Comment by hiyohiyoovo** [comment]
> > > 更新了新版本，请下载看看问题还有没有出现。 目前MAA框架我还没有研究出写本地的方法，所以暂时做不了。或许未来会实装，或许（
> > 
> > 
> > 新版本擁有了新的bugx 偶爾會不抽完就回倉庫，然後就退出了。
> 
> 狀況為UP十連抽完滑到普池不會進行抽取，就會直接回倉庫。

然後全部抽普池又出現錯誤了。nemu_connect instance_name: ginstance1393624695476708800
[2024-05-29 12:11:03.829][ERR][Px13488][Tx15190][ScreencapHelper.cpp][L71][MaaNS::CtrlUnitNs::ScreencapHelper::process_data] skip retry decoding and decode failed!
on_maafw_notify: Task.Started Clear_Data
on_maafw_notify: Task.Failed Clear_Data
### All tasks have been completed ###

**Comment by hiyohiyoovo** [comment]
[Uploading maa.log…]()

**Comment by hiyohiyoovo** [comment]
[maa.log](https://github.com/Carpenter-MK1/MaaHatsuboshiTA/files/15478648/maa.log)

**Comment by Carpenter-MK1** [comment]
> > > > 更新了新版本，请下载看看问题还有没有出现。 目前MAA框架我还没有研究出写本地的方法，所以暂时做不了。或许未来会实装，或许（
> > > 
> > > 
> > > 新版本擁有了新的bugx 偶爾會不抽完就回倉庫，然後就退出了。
> > 
> > 
> > 狀況為UP十連抽完滑到普池不會進行抽取，就會直接回倉庫。
> 
> 然後全部抽普池又出現錯誤了。nemu_connect instance_name: ginstance1393624695476708800 [2024-05-29 12:11:03.829][ERR][Px13488][Tx15190][ScreencapHelper.cpp][L71][MaaNS::CtrlUnitNs::ScreencapHelper::process_data] skip retry decoding and decode failed! on_maafw_notify: Task.Started Clear_Data on_maafw_notify: Task.Failed Clear_Data
> ### All tasks have been completed

最新版本尝试解决了这个问题，可以下载试一下。

**Comment by Carpenter-MK1** [comment]
对于mumu首页找不到按钮的问题，在设置中关闭后台保活即可。

**Comment by Rt39** [comment]
已经是最新版了但是这个issue似乎仍然存在，在第二次的时候必定失败，游戏版本为1.1.0，MaaPiCil版本为1.1.2，模拟器为BlueStacks Android 11

```
[2024-05-30 00:23:42.033][ERR][Px26884][Tx44563][MtouchHelper.cpp][L26][MaaNS::CtrlUnitNs::MtouchHelper::read_info] failed to read info
[2024-05-30 00:23:42.146][ERR][Px26884][Tx44563][MtouchHelper.cpp][L26][MaaNS::CtrlUnitNs::MtouchHelper::read_info] failed to read info
on_maafw_notify: Task.Started Clear_Data
on_maafw_notify: Task.Failed Clear_Data
### All tasks have been completed ###
```

希望能够添加自动重试功能，因为每次清除失败的时候都在主界面，可以重新开始

（已经在使用python脚本每隔7分钟communicate \n和6了
