### ISSUE TITLE
无法定位程序输入点

### ISSUE THREAD

**Issue by inoriyuzuha** [Carpenter-MK1/MaaHatsuboshiTA#9]
启动exe文件后显示无法定位程序输入点_std_free_crt于动态链接库上，路径全英文，最近三个版本都试过了报错都一样，MaaPiCli.exe，MaaToolkit.dll，MaaUtils.dll，MaaFramework.dll这四个一次弹出无法定位程序输入点

**Comment by lmii007** [comment]
我也是这个问题

**Comment by Carpenter-MK1** [comment]
看看这个 [issue](https://github.com/MaaXYZ/MaaFramework/issues/233) 能不能解决问题

**Comment by lmii007** [comment]
可以刷了，感谢！




林舜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Carpenter-MK1/MaaHatsuboshiTA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月30日(星期四) 下午2:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Carpenter-MK1/MaaHatsuboshiTA] 无法定位程序输入点 (Issue #9)





 
看看这个 issue 能不能解决问题
